#!/usr/bin/env python
from bottle import route, template, run, request, response
from cheese import mouse, keyboard

@route('/')
def index():
    return template('index')

"""
Mouse and Keyboard update routes
"""
@route('/mouse/moved', method='POST')
def mouse_moved():
    x = request.POST.get('x')
    y = request.POST.get('y')
    mouse.move(x, y)
    print 'Mouse moved! x: %s y: %s' % (x, y)

@route('/mouse/pressed', method='POST')
def mouse_pressed():
    button = request.POST.get('button')
    mouse.press(button)
    print 'Mouse pressed! button: %s' % button 

@route('/mouse/released', method='POST')
def mouse_released():
    button = request.POST.get('button')
    mouse.release(button)
    print 'Mouse released! button: %s' % button

@route('/keyboard/pressed', method='POST')
def keyboard_pressed():
    key = request.POST.get('key')
    ctrl = request.POST.get('ctrl', False)
    alt = request.POST.get('alt', False)
    shift = request.POST.get('shift', False)
    meta = request.POST.get('meta', False)
    keyboard.press(key)
    print 'Key pressed! key: %s ctrl: %s alt: %s shift: %s meta: %s' % (key, ctrl, alt, shift, meta)

@route('/keyboard/released', method='POST')
def keyboard_released():
    key = request.POST.get('key')
    ctrl = request.POST.get('ctrl', False)
    alt = request.POST.get('alt', False)
    shift = request.POST.get('shift', False)
    meta = request.POST.get('meta', False)
    keyboard.release(key)
    print 'Key released! key: %s ctrl: %s alt: %s shift: %s meta: %s' % (key, ctrl, alt, shift, meta)

@route('/static/:file')
def static_file(file):
    return open('static/%s' % file)

"""
Launch server
"""
run(host='localhost', port=1300)

